# Generated by Django 3.2.20 on 2023-07-18 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_rename_original_bag_order_original_basket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_profile',
            new_name='account_profile',
        ),
    ]
